### ISSUE TITLE
Webpack-dev-server version has reversed

### ISSUE THREAD

**Issue by kjacobsen** [Readify/readify-signatures#27]
@robdmoore's PR #22 has reverted my fixes in PR #20

**Comment by kjacobsen** [comment]
As its a manual fix, whatever tool generates `yarn.lock` picks a vulnerable version.

**Comment by kjacobsen** [comment]
Yeah react-scripts is on an old version that will cause it to pull down an old version of webpack-dev-server.

**Comment by robdmoore** [comment]
Oh weird. It was causing issues on my local build - I couldn't run it. Thoughts on what we should do? It should only affect local development right?
